QuizApp/WebApp/Controllers/ChoicesController.cs
using System;
using System.Threading.Tasks;
using Contracts.DAL.App;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL.App.DTO;
using Domain.App.Enums;
using Microsoft.AspNetCore.Authorization;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ChoicesController : Controller
    {
        private readonly IAppUnitOfWork _uow;

        public ChoicesController(IAppUnitOfWork uow)
        {
            _uow = uow;
        }

        // GET: Choices
        public async Task<IActionResult> Index()
        {
            return View(await _uow.Choices.GetAllAsync());
        }

        // GET: Choices/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var choice = await _uow.Choices.FirstOrDefaultAsync(id.Value);
            if (choice == null)
            {
                return NotFound();
            }

            return View(choice);
        }

        // GET: Choices/Create
        public IActionResult Create(Guid? question)
        {
            var vm = new ChoicesCreateEditViewModel()
            {
                Questions = new SelectList(_uow.Questions.GetAll(), nameof(Question.Id), nameof(Question.Title))
            };
            if (question.HasValue)
            {
                vm.Choice = new Choice
                {
                    QuestionId = question.Value
                };
            }
            return View(vm);
        }

        // POST: Choices/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ChoicesCreateEditViewModel vm)
        {
            if (ModelState.IsValid)
            {
                vm.Choice.Id = Guid.NewGuid();
                _uow.Choices.Add(vm.Choice);
                await _uow.SaveChangesAsync();
                return RedirectToAction("Details", "Questions", new {id = vm.Choice.QuestionId});
            }

            vm.Questions = new SelectList(await _uow.Questions.GetAllAsync(), nameof(Question.Id),
                nameof(Question.Title));
            return View(vm);
        }

        // GET: Choices/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vm = new ChoicesCreateEditViewModel()
            {
                Choice = await _uow.Choices.FirstOrDefaultAsync(id.Value)
            };
            if (vm.Choice == null)
            {
                return NotFound();
            }

            vm.Questions = new SelectList(await _uow.Questions.GetAllAsync(), nameof(Question.Id),
                nameof(Question.Title));
            return View(vm);
        }

        // POST: Choices/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, ChoicesCreateEditViewModel vm)
        {
            if (id != vm.Choice.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _uow.Choices.UpdateAsync(vm.Choice);
                    await _uow.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ChoiceExists(vm.Choice.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction("Details", "Questions", new {id = vm.Choice.QuestionId});
            }

            vm.Questions = new SelectList(await _uow.Questions.GetAllAsync(), nameof(Question.Id),
                nameof(Question.Title));
            return View(vm);
        }

        // GET: Choices/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var choice = await _uow.Choices
                .FirstOrDefaultAsync(id.Value);
            if (choice == null)
            {
                return NotFound();
            }

            return View(choice);
        }

        // POST: Choices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var choice = await _uow.Choices.FirstOrDefaultAsync(id);
            await _uow.Choices.RemoveAsync(choice);
            await _uow.SaveChangesAsync();
            return RedirectToAction("Details", "Questions", new {id = choice.QuestionId});
        }

        private bool ChoiceExists(Guid id)
        {
            return _uow.Choices.Any(e => e.Id == id);
        }
    }
}

QuizApp/WebApp/Controllers/QuestionsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Contracts.DAL.App;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL.App.DTO;
using Domain.App.Enums;
using Microsoft.AspNetCore.Authorization;
using WebApp.ViewModels;
using QuizSession = PublicApi.DTO.QuizSession;

namespace WebApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class QuestionsController : Controller
    {
        private readonly IAppUnitOfWork _uow;

        public QuestionsController(IAppUnitOfWork uow)
        {
            _uow = uow;
        }

        // GET: Questions
        public async Task<IActionResult> Index()
        {
            return View(await _uow.Questions.GetAllAsync());
        }

        // GET: Questions/Details/5
        public async Task<IActionResult> Details(Guid? id, QuestionDetDelViewModel vm)
        {
            if (id == null)
            {
                return NotFound();
            }

            vm.Question = await _uow.Questions
                .FirstOrDefaultAsync(id.Value);
            if (vm.Question == null)
            {
                return NotFound();
            }

            return View(vm);
        }

        // GET: Questions/Create
        public IActionResult Create(Guid? quiz)
        {
            var vm = new QuestionCreateEditViewModel
            {
                CorrectChoices = new SelectList(_uow.Choices.GetAll(), nameof(Choice.Id), nameof(Choice.Value)),
                Quizzes = new SelectList(_uow.Quizzes.GetAll(), nameof(Quiz.Id), nameof(Quiz.Title))
            };
            if (quiz.HasValue)
            {
                vm.Question = new Question
                {
                    QuizId = quiz.Value
                };
            }
            return View(vm);
        }

        // POST: Questions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(QuestionCreateEditViewModel vm)
        {
            if (ModelState.IsValid)
            {
                vm.Question.Id = Guid.NewGuid();
                _uow.Questions.Add(vm.Question);
                await _uow.SaveChangesAsync();
                return RedirectToAction("Details", "Quizzes", new {id = vm.Question.QuizId});
            }

            vm.CorrectChoices =
                new SelectList(await _uow.Choices.GetAllAsync(), nameof(Choice.Id), nameof(Choice.Value));
            vm.Quizzes = new SelectList(await _uow.Quizzes.GetAllAsync(), nameof(Quiz.Id), nameof(Quiz.Title));
            return View(vm);
        }

        // GET: Questions/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vm = new QuestionCreateEditViewModel()
            {
                Question = await _uow.Questions.FirstOrDefaultAsync(id.Value)
            };
            if (vm.Question == null)
            {
                return NotFound();
            }

            vm.CorrectChoices =
                new SelectList(await _uow.Choices.GetAllAsync(), nameof(Choice.Id), nameof(Choice.Value));
            vm.Quizzes = new SelectList(await _uow.Quizzes.GetAllAsync(), nameof(Quiz.Id), nameof(Quiz.Title));
            return View(vm);
        }

        // POST: Questions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, QuestionCreateEditViewModel vm)
        {
            if (id != vm.Question.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _uow.Questions.UpdateAsync(vm.Question);
                    await _uow.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!QuestionExists(vm.Question.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction("Details", "Quizzes", new {id = vm.Question.QuizId});
            }

            vm.CorrectChoices =
                new SelectList(await _uow.Choices.GetAllAsync(), nameof(Choice.Id), nameof(Choice.Value));
            vm.Quizzes = new SelectList(await _uow.Quizzes.GetAllAsync(), nameof(Quiz.Id), nameof(Quiz.Title));
            return View(vm);
        }
        
        // GET: Questions/Edit/5
        public async Task<IActionResult> EditCorrectChoice(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vm = new QuestionCreateEditViewModel()
            {
                Question = await _uow.Questions.FirstOrDefaultAsync(id.Value)
            };
            if (vm.Question == null)
            {
                return NotFound();
            }

            vm.CorrectChoices =
                new SelectList((await _uow.Choices.GetAllAsync()).Where(q => q.QuestionId.Equals(id)), nameof(Choice.Id), nameof(Choice.Value));
            vm.Quizzes = new SelectList(await _uow.Quizzes.GetAllAsync(), nameof(Quiz.Id), nameof(Quiz.Title));
            return View(vm);
        }

        // POST: Questions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditCorrectChoice(Guid id, QuestionCreateEditViewModel vm)
        {
            if (id != vm.Question.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _uow.Questions.UpdateAsync(vm.Question);
                    await _uow.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!QuestionExists(vm.Question.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction("Details", "Questions", new {id = vm.Question.Id});
            }

            vm.CorrectChoices =
                new SelectList(await _uow.Choices.GetAllAsync(), nameof(Choice.Id), nameof(Choice.Value));
            vm.Quizzes = new SelectList(await _uow.Quizzes.GetAllAsync(), nameof(Quiz.Id), nameof(Quiz.Title));
            return View(vm);
        }

        // GET: Questions/Delete/5
        public async Task<IActionResult> Delete(Guid? id, QuestionDetDelViewModel vm)
        {
            if (id == null)
            {
                return NotFound();
            }

            vm.Question = await _uow.Questions
                .FirstOrDefaultAsync(id.Value);
            vm.Choice = vm.Question.Choices.FirstOrDefault();
            if (vm.Question == null)
            {
                return NotFound();
            }

            return View(vm);
        }

        // POST: Questions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var question = await _uow.Questions.FirstOrDefaultAsync(id);
            if (question.CorrectChoiceId.HasValue) await _uow.Choices.RemoveAsync(question.CorrectChoiceId.Value);
            await _uow.Questions.RemoveAsync(question);
            await _uow.SaveChangesAsync();
            return RedirectToAction("Details", "Quizzes", new {id = question.QuizId});
        }

        private bool QuestionExists(Guid id)
        {
            return _uow.Questions.Any(e => e.Id == id);
        }
    }
}

QuizApp/WebApp/Views/Questions/_Shared/_CreateEdit.cshtml
@model QuestionCreateEditViewModel

<div asp-validation-summary="All" class="text-danger"></div>
<div class="form-group">
    <label asp-for="Question.Title" class="control-label"></label>
    <input asp-for="Question.Title" class="form-control"/>
    <span asp-validation-for="Question.Title" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Question.Description" class="control-label"></label>
    <input asp-for="Question.Description" class="form-control"/>
    <span asp-validation-for="Question.Description" class="text-danger"></span>
</div>
<input type="hidden" asp-for="Question.QuizId"/>
<input type="hidden" asp-for="Question.CorrectChoiceId"/>

QuizApp/WebApp/Views/Questions/_Shared/_DetailsDelete.cshtml
@model QuestionDetDelViewModel

<h4>Question</h4>
<hr/>
<div class="container">
    <h3 class="font-weight-bold">@Html.DisplayFor(model => model.Question.Title)</h3>
    <h5 class="font-weight-light">@Html.DisplayFor(model => model.Question.Description)</h5>
    <div class="float-right">
        <div class="small font-weight-light text-right">
            <div>
                Created by @Html.DisplayFor(model => model.Question.CreatedBy) at @Html.DisplayFor(model => model.Question.CreatedAt)
            </div>
            <div>
                Last changed by @Html.DisplayFor(model => model.Question.ChangedBy) at @Html.DisplayFor(model => model.Question.ChangedAt)
            </div>
        </div>
    </div>
    <br class="dropdown-divider"/>
    <table class="table w-75 text-center mx-auto my-5">
        <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Choice.Value)
            </th>
            <th>
                Answer count
            </th>
            <th>
                Actions
            </th>
            <th>
                Information
            </th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model.Question!.Choices!)
        {
            <tr class="@(item.Id.Equals(Model.Question.CorrectChoiceId) ? "alert-success" : "")">
                <td>
                    @Html.DisplayFor(modelItem => item.Value)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TimesAnswered) (@(Model.Question.TimesAnswered != 0 ? $"{item.TimesAnswered * 100 / Model.Question.TimesAnswered:0}%" : "0%"))
                </td>
                <td>
                    <div class="btn-group btn-group-sm">
                        <a class="btn btn-info text-white shadow-none" asp-controller="Choices" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                        <a class="btn btn-danger text-white shadow-none" asp-controller="Choices" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </div>
                </td>
                <td>
                    <div class="small font-weight-light">
                        <div>
                            Created by @Html.DisplayFor(modelItem => item.CreatedBy) at @Html.DisplayFor(modelItem => item.CreatedAt)
                        </div>
                        <div>
                            Last changed by @Html.DisplayFor(modelItem => item.ChangedBy) at @Html.DisplayFor(modelItem => item.ChangedAt)
                        </div>
                    </div>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>