QuizApp/WebApp/Controllers/QuizzesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Contracts.DAL.App;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL.App.DTO;
using Domain.App.Identity;
using Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class QuizzesController : Controller
    {
        private readonly IAppUnitOfWork _uow;

        public QuizzesController(IAppUnitOfWork uow)
        {
            _uow = uow;
        }

        // GET: Quizzes
        public async Task<IActionResult> Index()
        {
            return View(await _uow.Quizzes.GetAllAsync());
        }

        // GET: Quizzes/Details/5
        public async Task<IActionResult> Details(Guid? id, QuizzesDetDelViewModel vm)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            vm.Quiz = await _uow.Quizzes
                .FirstOrDefaultAsync(id.Value);
            if (vm.Quiz == null)
            {
                return NotFound();
            }

            return View(vm);
        }

        // GET: Quizzes/Create
        public IActionResult Create()
        {
            var vm = new QuizzesCreateEditViewModel();
            return View(vm);
        }

        // POST: Quizzes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(QuizzesCreateEditViewModel vm)
        {
            if (ModelState.IsValid)
            {
                vm.Quiz.Id = Guid.NewGuid();
                vm.Quiz.AppUserId = User.UserGuidId();
                _uow.Quizzes.Add(vm.Quiz);
                await _uow.SaveChangesAsync();
                return RedirectToAction(nameof(Details), new {id = vm.Quiz.Id});
            }

            return View(vm);
        }

        // GET: Quizzes/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vm = new QuizzesCreateEditViewModel()
            {
                Quiz = await _uow.Quizzes.FirstOrDefaultAsync(id.Value)
            };
            if (vm.Quiz == null)
            {
                return NotFound();
            }

            return View(vm);
        }

        // POST: Quizzes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, QuizzesCreateEditViewModel vm)
        {
            if (id != vm.Quiz.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _uow.Quizzes.UpdateAsync(vm.Quiz);
                    await _uow.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!QuizExists(vm.Quiz.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Details), new {id = vm.Quiz.Id});
            }

            return View(vm);
        }

        // GET: Quizzes/Delete/5
        public async Task<IActionResult> Delete(Guid? id, QuizzesDetDelViewModel vm)
        {
            if (id == null)
            {
                return NotFound();
            }

            vm.Quiz = await _uow.Quizzes
                .FirstOrDefaultAsync(id.Value);
            if (vm.Quiz == null)
            {
                return NotFound();
            }

            return View(vm);
        }

        // POST: Quizzes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var quiz = await _uow.Quizzes.FirstOrDefaultAsync(id);
            foreach (var question in quiz.Questions!)
            {
                if (question.CorrectChoiceId.HasValue) await _uow.Choices.RemoveAsync(question.CorrectChoiceId.Value);
                await _uow.Questions.RemoveAsync(question);
            }
            await _uow.Quizzes.RemoveAsync(quiz);
            await _uow.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool QuizExists(Guid id)
        {
            return _uow.Quizzes.Any(e => e.Id == id);
        }
    }
}

QuizApp/WebApp/Views/Quizzes/Create.cshtml
@model QuizzesCreateEditViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Quiz</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <partial name="_Shared/_CreateEdit"/>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

QuizApp/WebApp/Views/Quizzes/Delete.cshtml
@model QuizzesDetDelViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <partial name="_Shared/_DetailsDelete"/>
    <form asp-action="Delete">
        <input type="hidden" asp-for="@Model.Quiz.Id"/>
        <input type="submit" value="Delete" class="btn btn-danger"/> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

QuizApp/WebApp/Views/Quizzes/Details.cshtml
@model QuizzesDetDelViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <partial name="_Shared/_DetailsDelete"/>
    <div class="text-center">
        <a class="btn btn-success" asp-controller="Questions" asp-action="Create" asp-route-quiz="@Model.Quiz.Id">Add questions</a>
    </div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Quiz.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

QuizApp/WebApp/Views/Quizzes/Edit.cshtml
@model QuizzesCreateEditViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Quiz</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="All" class="text-danger"></div>
            <partial name="_Shared/_CreateEdit"/>
            <input type="hidden" asp-for="Quiz.Id"/>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Quizzes" asp-action="Details" asp-route-id="@Model.Quiz.Id">Back to Quiz</a>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

QuizApp/WebApp/Views/Quizzes/Index.cshtml
@using Domain.App.Enums
@model IEnumerable<DAL.App.DTO.Quiz>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
@foreach (var item in Model)
{
    <div class="card my-4">
        <div class="card-header text-left">
            <div class="d-flex justify-content-between m-2">
                <h4>
                    @if (item.QuizType == QuizType.Quiz)
                    {
                        <span class="badge badge-primary">Quiz</span>
                    }
                    else
                    {
                        <span class="badge badge-success">Poll</span>
                    }
                    @Html.DisplayFor(modelItem => item.Title)
                </h4>
                <div class="btn-group btn-group-sm">
                    <a class="btn btn-info text-white shadow-none" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                    <a class="btn btn-secondary text-white shadow-none" asp-action="Details" asp-route-id="@item.Id">Details</a>
                    <a class="btn btn-danger text-white shadow-none" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </div>
            </div>
            <div class="card card-body my-3">
                
                <div class="d-flex justify-content-between">
                    <div class="font-weight-light">
                        <p>
                            <span class="font-italic">Description: </span>@Html.DisplayFor(modelItem => item.Description)
                        </p>
                        This quiz/poll has been taken it @Html.DisplayFor(modelItem => item.TimesTaken) times.
                    </div>
                    <div class="font-weight-light small text-right">
                        <div>
                            Created by @Html.DisplayFor(modelItem => item.CreatedBy) at @Html.DisplayFor(modelItem => item.CreatedAt)
                        </div>
                        <div>
                            Last changed by @Html.DisplayFor(modelItem => item.ChangedBy) at @Html.DisplayFor(modelItem => item.ChangedAt)
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}